name: "Test builds"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        package: [ "libusb", "fcitx5-nord", "bibata" ]
        arch: [ "aarch64-linux", "i686-linux", "x86_64-linux" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
    
    - uses: docker/setup-qemu-action@v1
      if: ${{ matrix.arch == 'aarch64-linux' }}
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64

    - run: |-
          nix -L build \
              --system ${{ matrix.arch }} \
              .#${{ matrix.package }}
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake check
